// Utilities
import type { Metadata } from "next";

// Fonts
import { Roboto } from "next/font/google";

// Styles
import "./globals.css";

const robotoFont = Roboto({
   subsets: ["latin"],
   weight: ["400", "700"],
});

export const metadata: Metadata = {
   title: "BibleChat Technical Challenge",
   description: "Mares Mihai-Gabriel, app generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${robotoFont.className} grid items-center m-0`}>{children}</body>
      </html>
   );
}
